### ISSUE TITLE
`CloseSubscription` abstract operation missing?

### ISSUE THREAD

**Issue by isiahmeadows** [tc39/proposal-observable#105]
I've noticed, while implementing a minimal spec-matching ponyfill (no extras), that there's a call to an abstract operation called "CloseSubscription" in [%SubscriptionObserverPrototype%.next](https://tc39.github.io/proposal-observable/#subscription-observer-prototype-next), but that operation isn't defined elsewhere.

Should that be fixed to implement [zen-observable's algorithm](https://github.com/zenparsing/zen-observable/blob/4cd5fbe301a5e64fce1eecef4f83258c3b718efb/src/Observable.js#L66-L73) (detailed below)?

> 5.1.??? CloseSubscription(*subscription*)
>
> 1. Assert: Type(*subscription*) is Object.
> 2. Assert: *subscription* is a Subscription Observer object.
> 3. If SubscriptionClosed(*subscription*) is **true**, then return **undefined**.
> 4. Set *subscription*'s [[Observer]] slot to **undefined**.
> 5. Return ? CleanupSubscription(*subscription*).

**Comment by zenparsing** [comment]
Thanks @isiahmeadows for the catch. I think the original intent was to just inline the steps, which I just did in ad0699aee6554dfd000da27b47a7ff0e39edbfa4 .
