### ISSUE TITLE
Add toPromise function.

### ISSUE THREAD

**Issue by lygstate** [tc39/proposal-observable#124]

**Comment by ljharb** [comment]
I believe you can use `.forEach()` to get a Promise out

**Comment by satya164** [comment]
@lygstate what'd the Promise resolve to?

**Comment by lygstate** [comment]
The first value of next
.subscribe(resolve, reject)

**Comment by benjamingr** [comment]
Yes, this is `.forEach`.

**Comment by lygstate** [comment]
@benjamingr  That's a different things, .forEach return a promise thath resolve void.
but .subscribe(resolve, reject) resolve the fist value of Observable events

**Comment by benjamingr** [comment]
This proposal doesn't even add things like `.map`, an Rx like `toPromise` is not in scope for the proposal.

**Comment by satya164** [comment]
@lygstate If you want to use in an async function, and the observable actually gives a single value, probably this works?

```js
let x;
await observable.forEach(value => x = value);
```

Though the `toPromise` in RxJS returns the last value instead and not the first value.

**Comment by lygstate** [comment]
@satya164 Sometimes, we need chained the function for programing.
How about to make the first parameter of forEach to be optional,
if the first parameter is NULL, then return 
Promise<Array>

**Comment by satya164** [comment]
@lygstate Until there's any discussion about adding `toPromise`, I think it's pretty easy to write a function yourself to do that, which you can use for chaining.

The behaviour you're suggesting doesn't sound very intuitive and I think will be confusing.

**Comment by lygstate** [comment]
@satya164 Cause Promise is a standard EcmaScript feature, so converting between these two objects in standard way are necessary.

**Comment by satya164** [comment]
@lygstate yes, but I'd rather follow the RxJS API for that. though we first need to get observables into the language. adding `toPromise` can come after that.

**Comment by pitaj** [comment]
@satya164 I'd rather not be in another position where people are using a third party library like Bluebird to patch in `Promise.finally`.

**Comment by ljharb** [comment]
@pitaj https://github.com/tc39/proposal-promise-finally - there's nothing wrong with a window between standardization of the primitive and standardization of the nicer convenience methods that expand on it.

**Comment by pitaj** [comment]
@ljharb I disagree. There certainly is something wrong with this method not existing, and that is a cost of more overhead for developers. Whether the degree of wrong is beyond the benefit gained by it not being in the original spec is another question.

**Comment by jhusain** [comment]
No objection to having such a method. Seems like we need to settle the issue over the completion value first. At the moment I do not believe that Observable should forward a completion value. This would open up the question of what toPromise should return. This  is a good indication to me that this is an issue best settled after the proposal's been standardized.

**Comment by lygstate** [comment]
Maybe resolve with a list of entries.?
