### ISSUE TITLE
Operator examples

### ISSUE THREAD

**Issue by nmuldavin** [tc39/proposal-observable#175]
I just wrapped work on a first pass [library of reactive Operators](https://github.com/nmuldavin/ObservableOperators) built directly on top of this proposal. This is a bit of a shameless plug, but I thought it might be an interesting test case for the proposal itself to see what it takes to write such operators. I'd gladly welcome any feedback or PRs.

**Comment by benjamingr** [comment]
Actually, @blesh wrote RxJS 5 on top of this proposal. 

Nice demo anyway :)
