### ISSUE TITLE
Design bikeshed

### ISSUE THREAD

**Issue by benjamingr** [tc39/proposal-observable#98]
Hey, 

Just bikeshedding some design considerations for a cancellable promise canellation token based design:

``` js

Observable.of(3).subscribe(x => console.log(x)); // this doesn't change

// the two other callbacks
Observable.of(3).subscribe(x => console.log(x))
                           .then(() => console.log("Completed"))
                           .catch() => console.log("Error handle entire stream here"));

// Cancellation handling 
const events = domNode.events("keyup")/*.map(x => x.target.value)*/
const { token, cancel } = CancelToken.source(); // bikeshed from domenic from https://github.com/zenparsing/es-cancel-token/issues/3
events.subscribe(token);
events.cancel();

// Alternatively 
const events = domNode.events("keyup")/*.map(x => x.target.value)*/
// return a promise with a cancel property based on a cancellation token
var subscription = events.subscribe(token); 
subscription.cancel(); // creates the token/cancel pair internally and exports cancel.
```

---

Feel free to skip reading this part:

I implemented my own FRP library in C# a while back in TipRanks for specific things Rx was too broad for, the approach we took was similar (and token based). Our `subscribe` is called `Run` and it returns a task.

This is effectively very similar to this design. Here is a piece that's literally in our code base to demonstrate what it looks like:

``` c#
await Create("Master Machine Tasks").Concurrently(
    Of(UpdateMostRecStocksCache).Log("Updated Most Rec Stocks").Delay(TimeSpan.FromHours(2)).Repeat(),
    Of(UpdateInsidersHotStocksCache).Log("Updated Hot Stocks").Delay(TimeSpan.FromHours(2)).Repeat(),
    Of(UpdateLiveFeedCache).Log("Updated Live Feed Cache").Delay(TimeSpan.FromMinutes(2)).Repeat(),
    Of(StartQueueInformerTask).Delay(TimeSpan.FromMinutes(60)).Repeat(),
    Of(UpdateTrendingStocksCache).Log("Updated Trending Stocks").Delay(TimeSpan.FromHours(2)).Repeat(),
    Of(EnsureUpdateAllCacheGetsSentEvery24Hours).Delay(TimeSpan.FromHours(1)).Repeat(),
    Of(PollForUpdateAllCache).Delay(TimeSpan.FromSeconds(1)).Repeat(),
    Of(autoCompleter.StoreAutoCompleteDataInCache).Log("Updated autocomplete blob cache").Delay(TimeSpan.FromHours(3)).Repeat(),
    Of(UpdateExpertOperationDistribution).Log("Updated expert operation distribution cache").Delay(TimeSpan.FromHours(3)).Repeat(),
    Of(UpdateStockEvents).Log("Updated stock events").Delay(TimeSpan.FromHours(12)).Repeat(),
    Of(UpdateStockIdTickerMapping).Log("Updated stock id to ticker mapping").Delay(TimeSpan.FromHours(1)).Repeat(),
    Of(UpdateOldPortfoliosBeta).Log("Updated portfolio betas").Delay(TimeSpan.FromHours(8)),
    Of(UpdateAveragePortfolio).Log("Updated Avg. Portfolio").Delay(TimeSpan.FromHours(6)).Repeat(),
    Of(UpdateMarketsOverviewOneDayPrices).Log("Updated MarketsOverviewOneDayPrices").Delay(TimeSpan.FromHours(1)).Repeat(),
    Of(UpdateSeoPagesSitemap).Log("Updated Seo Sitemap pages").Delay(TimeSpan.FromHours(1)).Repeat(),
    Of(UpdateMigratedUsersToNewDashboard).Log($"Updated {nameof(UpdateMigratedUsersToNewDashboard)}").Delay(TimeSpan.FromHours(1)).Repeat(),
    Of(UpdateNumOldPortfolios).Log("Updated numOldPortfolios").Delay(TimeSpan.FromHours(5)).Repeat(),
    Of(DeleteCacheLogs).Log("Deleted cache logs").Delay(TimeSpan.FromHours(1)).Repeat(),
    Of(DeleteGeneralLogs).Log("Deleted general logs").Delay(TimeSpan.FromHours(1)).Repeat()
).RunAsync(out _cts);
```

Note that while the code is verbose it launches a lot of concurrent tasks declaratively. I have operators like `Concurrently` and `Select` so on. It's cute and we use it a lot - it's hardly really FRP since it does a lot of side effects.

A pipeline has a logger and error handler attached, it returns a `Task` and exports a `CancellationTokenSource`. This is surprisingly similar to the design the TC is looking at with the exception JavaScript has no out parameters.

**Comment by blesh** [comment]
Don't cancellation tokens only flag intent to cancel? Observable needs to execute code on unsubscribe.

Also, all errors are going to fall into the promise trap. That's a huge negative.

Is there a valid technical reason to alter the type to use cancelable promises?

**Comment by blesh** [comment]
What does the observable definition look like? `new Observable((observer, token) => ????)`

**Comment by blesh** [comment]
How do we compose composite unsubscriptions with cancelable promises? like flatMap? Share a token I assume? What about groupBy?

**Comment by benjamingr** [comment]
> Don't cancellation tokens only flag intent to cancel? Observable needs to execute code on unsubscribe.

Cancellation tokens mean request of cancellation. Observalbes can execute code when they run. Guarantees are the same.

> Also, all errors are going to fall into the promise trap. That's a huge negative.

There is no such thing as "the promise trap". Promise exceptions are never swallowed and are reported to a handler if not awaited. With the intended use with `await` errors will be thrown to the function containing them which will actually be nicer since it will use try catch.

> Is there a valid technical reason to alter the type to use cancelable promises?

I'm not a fan of this design but I want to see this proposal finally move forward. This is the direction the TC wants to move forward. The reasons presented by Domenic are: lower API surface, fewer abstractions developer have to learn and interoperability with other DOM APIs.

> What does the observable definition look like? `new Observable((observer, token) => ????)`

I don't see why it would look very different - you would `return` the unsubscribe function. Observables need to specify how to cancel - and not treat the token:
```js
new Observable(observer => {
   return () => { /* cancel code here */}
});
```

An alternative design (which I am not proposing here at all) would be: 

```js
new Observable((observer, token) => {
    // logic
    token.cancelled().then(() => ... });
});
```

But that would be quirky and strange.

> How do we compose composite unsubscriptions with cancelable promises?

If we want to wait for multiple tokens to be cancelled: `Promise.all`, if we want to wait for the first one: `Promise.race`.

>  like flatMap? Share a token I assume? 

Yes, `flatMap` would take a token parameter in addition to the value and pass it when needed. Like in https://github.com/zenparsing/es-observable/pull/97#issuecomment-222387050 .

> What about groupBy?

Similarly, note that there is nothing preventing observables from being directly cancellable and exposing a `.token` property directly or even a `.cancel` function directly.

We can also alternatively argue a case that cancellation and unsubscription are fundamentally different - indeed in my mind they are (and they are different types in the C# - Cancellation is with CancellationToken and observables dispose with subscriptions although CancellationToken is there).

**Comment by domenic** [comment]
> An alternative design (which I am not proposing here at all) would be: 

This is what I was anticipating; there's no reason to hide the cancelation registration behind layers of sugar unlike what other cancelable parts of the web platform would use.

Similarly it's not clear we'd want to hide the ability to cancel behind a `.cancel()` method instead of using the token's cancelation ability, like everything else will use. In this way you can entirely get rid of the subscription type, as @jhusain and I were discussing at TC39.

**Comment by blesh** [comment]
I'd still like some technical justification for a change in design. It doesn't seem right to build on top of two other primitives that are not even in the spec. I feel it hurts the ergonomics of the type and makes this spec more brittle.

If it's a matter of removing the subscription type, I'm okay with returning a function or even returning a token over anything involving cancelable promise.

**Comment by blesh** [comment]
In that vein, Most.js has a design where you can pass a subscription object into a subscription, or just have one returned. That's a possible use case for cancellation token. You can either give it one, or one will be returned.
